//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityServicesTemp
    {
        public long ID { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string StateCode { get; set; }
        public string ParentServiceName { get; set; }
        public string ServiceName { get; set; }
        public string ZipCodeStr { get; set; }
        public string CityDescription { get; set; }
        public string ServiceCityContent { get; set; }
        public string PageTitle { get; set; }
        public string MetaDescription { get; set; }
        public string PageH1Content { get; set; }
        public string PageH2Content { get; set; }
        public string MetaKeyword { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public string VideoLink { get; set; }
        public string UploadUniqueKey { get; set; }
    }
}
