//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityDetailMaster
    {
        public int ID { get; set; }
        public int CityServiceDetailId { get; set; }
        public string PageTitle { get; set; }
        public string ZipCodeStr { get; set; }
        public string CityDescription { get; set; }
        public string MetaDescription { get; set; }
        public string PageH1Content { get; set; }
        public string PageH2Content { get; set; }
        public string MetaKeyword { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VideoLink { get; set; }
    }
}
