//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintReply
    {
        public long ID { get; set; }
        public long ComplaintID { get; set; }
        public string ReplyMessage { get; set; }
        public string ReplyByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Complaint Complaint { get; set; }
    }
}
