//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentManagerICO
    {
        public long ID { get; set; }
        public string H1BoldText { get; set; }
        public string H1StrongText { get; set; }
        public string H2Tag { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string VideoTagLine { get; set; }
        public Nullable<bool> IsShowVideo { get; set; }
        public string VideoLink { get; set; }
    }
}
