//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUploadSetting
    {
        public long ID { get; set; }
        public long QuestionID { get; set; }
        public Nullable<long> MaxNumberID { get; set; }
        public Nullable<long> SizeID { get; set; }
        public string FileTypeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual AllowFileMaxNumber AllowFileMaxNumber { get; set; }
        public virtual AllowFileMaxSize AllowFileMaxSize { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
