//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetAllConnectedUserList_Result1
    {
        public string UserID { get; set; }
        public long GroupID { get; set; }
        public long JobID { get; set; }
        public string JobTitle { get; set; }
        public string UserImage { get; set; }
        public string UserName { get; set; }
        public string UserShortName { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
    }
}
