//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetExistingPostedOrderList_Result1
    {
        public long ID { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long ServiceID { get; set; }
    }
}
