//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetLatestOrderList_Result3
    {
        public long ID { get; set; }
        public string JobTitle { get; set; }
        public long ServiceID { get; set; }
        public string ServicePic { get; set; }
        public Nullable<int> ReceivedBid { get; set; }
        public Nullable<System.DateTime> JobExpireDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
