//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetMessageChatWithUser_Result3
    {
        public long JobID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public long GroupId { get; set; }
        public string BlockByID { get; set; }
        public string BlockBy { get; set; }
        public string JobCompleted { get; set; }
        public string HiredStatus { get; set; }
        public string ToUserName { get; set; }
    }
}
