//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetProposalUserList_Result3
    {
        public long JobID { get; set; }
        public string UserID { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsBidLock { get; set; }
        public Nullable<System.DateTime> CreatedProposalDate { get; set; }
        public string location { get; set; }
        public Nullable<int> MyGigsCount { get; set; }
        public Nullable<int> MyBidsCount { get; set; }
        public Nullable<int> ThumbsUp { get; set; }
        public Nullable<int> ThumbsDown { get; set; }
        public string CustomerStatus { get; set; }
        public Nullable<long> ProposalID { get; set; }
        public bool IsUnlimitedBidView { get; set; }
        public string SPStatus { get; set; }
        public string HiredStatus { get; set; }
        public string UserName { get; set; }
        public string ProfilePic { get; set; }
        public int IsInvited { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
