//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetReviewRatingList_Result3
    {
        public string UserName { get; set; }
        public bool ThumbsValue { get; set; }
        public string Review { get; set; }
        public string WorkAgain { get; set; }
        public string JobTitle { get; set; }
        public string UserImage { get; set; }
    }
}
