//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetUserDetailById_Result1
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public int BidPoints { get; set; }
        public string ProfessionalTitle { get; set; }
        public string ProfessionalDescription { get; set; }
        public string PlanName { get; set; }
        public Nullable<int> ThumbsUp { get; set; }
        public Nullable<int> ThumbsDown { get; set; }
        public Nullable<int> MyGigsCount { get; set; }
        public Nullable<int> MyBidsCount { get; set; }
        public string UserShortName { get; set; }
        public string ProfilePic { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
