//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetUserList_Result1
    {
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public int Quigs { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string CountryName { get; set; }
        public string Zipcode { get; set; }
        public string UserRole { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public Nullable<System.DateTime> LockoutDate { get; set; }
        public string UserPlan { get; set; }
        public string PhoneNo { get; set; }
    }
}
