//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class GetUserMessageList_Result3
    {
        public string FromUserID { get; set; }
        public string MessageText { get; set; }
        public string ToUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ToUserImage { get; set; }
        public string FromUserImage { get; set; }
        public string FromUserShortName { get; set; }
        public string ToUserShortName { get; set; }
    }
}
