//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOptionAttachment
    {
        public long ID { get; set; }
        public long JobQuestionOptionsID { get; set; }
        public string OriginalName { get; set; }
        public string NewName { get; set; }
        public string Path { get; set; }
        public string AttachmentExt { get; set; }
        public string AttachmentType { get; set; }
        public decimal AttachmentSize { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Description { get; set; }
    
        public virtual JobQuestionOption JobQuestionOption { get; set; }
    }
}
