//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobQuestionOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobQuestionOption()
        {
            this.JobOptionAttachments = new HashSet<JobOptionAttachment>();
        }
    
        public long ID { get; set; }
        public long OptionID { get; set; }
        public string OtherAnswer { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long JobID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOptionAttachment> JobOptionAttachments { get; set; }
        public virtual Job Job { get; set; }
        public virtual QuestionOption QuestionOption { get; set; }
    }
}
