//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageCampain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManageCampain()
        {
            this.UserICOWallets = new HashSet<UserICOWallet>();
        }
    
        public int Id { get; set; }
        public string CampainName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public long TokenSize { get; set; }
        public decimal TokenPrice { get; set; }
        public decimal IncreaseBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public long SellOutToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserICOWallet> UserICOWallets { get; set; }
    }
}
