//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageGroupMember
    {
        public long ID { get; set; }
        public long GroupId { get; set; }
        public string MemberId { get; set; }
        public bool IsBlock { get; set; }
        public string BlockByID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MessageGroup MessageGroup { get; set; }
    }
}
