//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionControl
    {
        public long ID { get; set; }
        public string ControlName { get; set; }
        public string UniqueName { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string UpdatedByID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
