//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDuration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanDuration()
        {
            this.PlanDurationFeatures = new HashSet<PlanDurationFeature>();
        }
    
        public long ID { get; set; }
        public long PlanID { get; set; }
        public long DurationID { get; set; }
        public int DurationValue { get; set; }
        public decimal DurationAmount { get; set; }
        public Nullable<int> FreeTrial { get; set; }
    
        public virtual Duration Duration { get; set; }
        public virtual SubscriptionPlan SubscriptionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDurationFeature> PlanDurationFeatures { get; set; }
    }
}
