//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDurationFeature
    {
        public long ID { get; set; }
        public long FeatureID { get; set; }
        public long PlanDurationID { get; set; }
        public bool IsFeeAndUnlimited { get; set; }
        public string FeatureValue { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual PlanDuration PlanDuration { get; set; }
    }
}
