//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class proc_AdminQuigsStats_Result2
    {
        public Nullable<long> TotalQuigs { get; set; }
        public Nullable<long> SoldQuigs { get; set; }
        public Nullable<long> AvailableQuigs { get; set; }
        public Nullable<long> SoftTarget { get; set; }
        public Nullable<long> HardTarget { get; set; }
        public Nullable<decimal> CurrentQuigsVal { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
