//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    
    public partial class proc_GigsSaleReport_Result2
    {
        public string UserName { get; set; }
        public int BonusCoin { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Token { get; set; }
        public string UserEmail { get; set; }
        public Nullable<long> QuigsSale { get; set; }
        public string PaymentFrom { get; set; }
        public Nullable<long> TotalQuigs { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string Description { get; set; }
        public string SaleStatus { get; set; }
    }
}
