//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proposal()
        {
            this.Hireds = new HashSet<Hired>();
        }
    
        public long ID { get; set; }
        public long JobID { get; set; }
        public string UserID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string Skills { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public int BidPoint { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ProposalStatus { get; set; }
        public string SPStatus { get; set; }
        public string CustomerStatus { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsBidLock { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hired> Hireds { get; set; }
        public virtual Job Job { get; set; }
    }
}
