//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public long ID { get; set; }
        public string RefundToID { get; set; }
        public Nullable<long> JobID { get; set; }
        public decimal RefundAmount { get; set; }
        public string RefundByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Job Job { get; set; }
    }
}
