//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewRating
    {
        public long ID { get; set; }
        public string FromID { get; set; }
        public string ToID { get; set; }
        public string Review { get; set; }
        public int Rating { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool ThumbsValue { get; set; }
        public Nullable<bool> IsWorkAgain { get; set; }
        public Nullable<long> JobID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Job Job { get; set; }
        public virtual Job Job1 { get; set; }
        public virtual Job Job2 { get; set; }
    }
}
