//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedOrder
    {
        public long ID { get; set; }
        public long JobID { get; set; }
        public Nullable<System.DateTime> JobExpireDate { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Job Job { get; set; }
    }
}
