//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeeLowestBid
    {
        public long ID { get; set; }
        public long JobId { get; set; }
        public string UserId { get; set; }
        public decimal Amount { get; set; }
        public bool IsShow { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Job Job { get; set; }
    }
}
