//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServiceArea
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string Zipcode { get; set; }
        public Nullable<long> TravellingID { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CustomerTravellingArea CustomerTravellingArea { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
