//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> TimeZoneID { get; set; }
        public string ProfilePic { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public string UserEmailCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedByID { get; set; }
        public string UpdatedByID { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int BidPoints { get; set; }
        public string ProfessionalTitle { get; set; }
        public string ProfessionalDescription { get; set; }
        public string WebSiteUrl { get; set; }
        public bool IsPublish { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CarryForwordCoin { get; set; }
        public string UserSignUpComplete { get; set; }
        public string IpAddress { get; set; }
        public string Location { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual TimeZone TimeZone { get; set; }
    }
}
