//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPayment
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public Nullable<long> UserPlanId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public string PaymentStatus { get; set; }
        public string Token { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PaymentFrom { get; set; }
        public Nullable<long> PackageId { get; set; }
        public Nullable<decimal> TransactionFee { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PaymentSubscription PaymentSubscription { get; set; }
        public virtual QuigsPackage QuigsPackage { get; set; }
        public virtual QuigsPackage QuigsPackage1 { get; set; }
        public virtual QuigsPackage QuigsPackage2 { get; set; }
        public virtual UserPlan UserPlan { get; set; }
    }
}
