//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserICOWallet
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CampainID { get; set; }
        public Nullable<decimal> TokenPrice { get; set; }
        public Nullable<long> NoOfToken { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TransactionID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ManageCampain ManageCampain { get; set; }
    }
}
