//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWallet
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public Nullable<long> UserPaymentId { get; set; }
        public string Description { get; set; }
        public decimal CreditAmount { get; set; }
        public decimal DebitAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PaymentFrom { get; set; }
        public Nullable<long> PackageId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<int> BonusCoin { get; set; }
        public string PaymentGateway { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual QuigsPackage QuigsPackage { get; set; }
        public virtual QuigsPackage QuigsPackage1 { get; set; }
        public virtual QuigsPackage QuigsPackage2 { get; set; }
    }
}
