//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserService
    {
        public long ID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public Nullable<long> UserAreaID { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string UserID { get; set; }
        public bool IsDraft { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Service Service { get; set; }
    }
}
