//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDoc
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string DocumentType { get; set; }
        public string DocumentExt { get; set; }
        public string DocumentPath { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsVerified { get; set; }
        public string VerifiedByID { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
