//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiGigAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBidHistory
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string Summary { get; set; }
        public int BidCr { get; set; }
        public int BidDr { get; set; }
        public System.DateTime CratedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
